app_json = JSON.parse(File.read("../app.json"))
package = app_json["expo"]["android"]["package"]

File.write("Appfile", <<~APPFILE)
  package_name "#{package}"
APPFILE

lane :deploy do
  build_number = google_play_track_version_codes(track: "internal").max + 1
  app_json["expo"]["android"]["versionCode"] = build_number
  File.write("../app.json", JSON.pretty_generate(app_json) + "\n")
  sh("cd .. && npx expo prebuild --platform android")
  gradle(task: "bundleRelease", project_dir: "android")
  supply(
    aab: "android/app/build/outputs/bundle/release/app-release.aab",
    track: "internal",
    metadata_path: "fastlane/android",
  )
  slack
end

error do |lane, exception|
  slack(message: exception.message, success: false)
end
